volumes:
  db:

networks:
  default:
    
services:
  app:
    container_name: yamb-bot-dev
    build:
      # change context to copy local repo during development
      context: ../
      dockerfile: docker/Dockerfile
    image: ruined/yamb-dev
    ports:
      - "5000:5000"
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - default
    env_file:
      - app.dev.env

  db:
    container_name: yamb-db-dev
    image: postgres:16
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - default
    env_file:
      - db.dev.env